%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: D:\Dropbox (Cognitive and Affective Neuroscience Laboratory)\V_visceral_common\scripts\Visceral_pain_master_sheet_v2.xlsx
%    Worksheet: Data
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2018/10/05 13:27:23

%% Import the data
[~, ~, raw] = xlsread('D:\Dropbox (Cognitive and Affective Neuroscience Laboratory)\V_visceral_common\scripts\Visceral_pain_master_sheet_v2.xlsx','Data','A2:T221');
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
cellVectors = raw(:,[1,3,5,6,7,17,19,20]);
raw = raw(:,[2,4,8,9,10,11,12,13,14,15,16,18]);

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
Dir_Name1 = cellVectors(:,1);
Study1 = data(:,1);
Patient_group1 = cellVectors(:,2);
Subject_name1 = data(:,2);
Beta_image_folder_name1 = cellVectors(:,3);
Pain_type1 = cellVectors(:,4);
Stimulation_site1 = cellVectors(:,5);
Stimulus_intensity1 = data(:,3);
Average_VAS_pain1 = data(:,4);
Average_VAS_nopain1 = data(:,5);
Run1_VAS_pain_nopain1 = data(:,6);
Run2_VAS_pain_nopain1 = data(:,7);
Run3_VAS_pain_nopain1 = data(:,8);
Run4_VAS_pain_nopain1 = data(:,9);
Run5_VAS_pain_nopain1 = data(:,10);
Run6_VAS_pain_nopain1 = data(:,11);
Symptom_severity1 = cellVectors(:,6);
Age1 = data(:,12);
Gender1 = cellVectors(:,7);
Stimulus_intensity_pressure1 = cellVectors(:,8);

%% Clear temporary variables
clearvars data raw cellVectors R;